apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: clickhouse-cert
    app.kubernetes.io/managed-by: kustomize
  name: clickhouse-cert
  namespace: default
spec:
  dnsNames:
    - "*.sample-clickhouse-headless.default.svc"
    - "*.sample-clickhouse-headless.default.svc.cluster.local"
  subject:
    organizations:
      - sample-ch
  issuerRef:
    kind: Issuer
    name: local-issuer
  secretName: clickhouse-cert
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample
spec:
  replicas: 1
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  keeperClusterRef:
    name: sample
  settings:
    tls:
      enabled: true
      required: true
      serverCertSecret:
        name: clickhouse-cert